site_name: ZIJI-CS-FundamentalDataStructure # TODO: 请修改项配置，将尖括号内的内容替换为课程名称
repo_name: ZIJI-CS/T-FundamentalDataStructure # TODO: 请修改项配置，将其设置为对应的仓库
repo_url: https://github.com/ZIJI-CS/T-FundamentalDataStructure # TODO: 请修改项配置，将其设置为对应的仓库的 URL，一般替换后缀即可
edit_uri: blob/main/docs
use_directory_urls: false  # 加上这句后才能显示用 html img 相对路径插入的图片

copyright: 'Copyright &copy 2024 ZIJI-CS' # TODO: 请修改项配置，主要就是年份，对的就不用管

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt
    edit: material/pencil
    view: material/eye
  # custom_dir: overrides # TODO: 请根据指导配置完 Giscus 后再取消注释：https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/
  # 没开放 Discussions，不能启用该功能

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - admonition
  - pymdownx.details
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
  - search:
      separator: '[\s\-\.]+'
  - git-committers:
      repository: ZIJI-CS/T-FundamentalDataStructure # TODO: 请修改本项配置，一般同步于 repo_name 即可（如果主分支不叫 main 也请修改 branch 项）
      branch: main
  - statistics:
      words_per_minute: 200
  - glightbox

extra_css:
  # 如果需要修改主题样式，可以修改 `theme.css`；如果需要修改 admonitions 的主题，可以修改 `admonitions.css`
  - supports/css/base.css
  - supports/css/theme.css
  - supports/css/admonitions.css
  - supports/css/custom-adms.css
  # 如果公式渲染样式出现问题，请检查如下脚本
  - https://jsd.cdn.zzko.cn/npm/katex@0.16.4/dist/katex.min.css

extra_javascript:
  # 自动令所有第三方链接在新标签页中打开
  - supports/js/xlink.js
  # 如果公式渲染出现问题，请检查如下脚本
  - supports/js/katex.js
  - https://jsd.cdn.zzko.cn/npm/katex@0.16.4/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

# ======================================== >>>
# TODO: 请修改本项配置，本节是导航配置项，一般只需要在下面增加新的章节对应的文件即可，支持结构化配置

nav:
  - "Home": "https://ziji-cs.github.io/"
  - "Main":
    - "index.md"
    - "2-x.md"
    - "3-x.md"
    - "4-x.md"
    - "5-x.md"
    - "6-x.md"
    - "7-x.md"
    - "8-x.md"
    - "9-x.md"
  # - "Appendix":

# ======================================== <<<

